### ISSUE TITLE
Can anyone help me?

### ISSUE THREAD

**Issue by Scarpy19** [codymullins/dotnet-tailwind#3]
I dont know what i did wrong, I installed on an .NET 8.0 project like this:

dotnet new tool-manifest # if you are setting up this repo
dotnet tool install --local Tailwind --version 0.6.1

And i got this error after run

dotnet tailwind init

![image](https://github.com/codymullins/dotnet-tailwind/assets/63962989/72824d68-506e-4e15-8535-8513c6d79f8f)

**Comment by tesar-tech** [comment]
It seems you don't have dotnet sdk installed.
Try: `dotnet --list-sdks`

I guess it will again output `dotnet SDK not found`..
Install dotnet https://dotnet.microsoft.com/en-us/download

**Comment by Scarpy19** [comment]
I have it installed

![image](https://github.com/codymullins/dotnet-tailwind/assets/63962989/c4006f6e-cac7-4328-9e87-241382c84896)

**Comment by codymullins** [comment]
Hmm. Interesting. @Scarpy19 I will take a look later today. By chance have you tried restarting your computer?

**Comment by Scarpy19** [comment]
Nope, I'll try it when I can

**Comment by codymullins** [comment]
@Scarpy19 I also just published v0.7.0-alpha, please try that when you can.

**Comment by Scarpy19** [comment]
@codymullins v0.7.0-alpha working smoothly, thanks

![image](https://github.com/codymullins/dotnet-tailwind/assets/63962989/c407b20a-00c6-403d-9a39-6b5d0396014e)

**Comment by codymullins** [comment]
great! let me know if you run into any other issues.
